"""
Transparency Label Builder — the human-facing text shown to readers.

Implements the three label variants from planning.md §1 Step 6.

Gating logic:
  - confidence < 0.80  →  Label C (Uncertain) — always, regardless of label
  - label == "ai"      →  Label A (High-confidence AI)
  - label == "human"   →  Label B (High-confidence Human)
  - else               →  Label C (Uncertain)

This means a 0.51 classification and a 0.95 classification produce
meaningfully different user-facing text, even if both have the same
binary label.  Confidence gates the transparency label, not just the
score field — this is the central design principle.
"""

# ---------------------------------------------------------------------------
# Label variant text (exact prose from planning.md)
# ---------------------------------------------------------------------------

LABEL_A = """AI-Generated Content — High Confidence

Our detection system is strongly confident that this text was generated \
by artificial intelligence. Two independent signals — a semantic analysis \
by an AI model and a statistical analysis of the writing's structure — \
both point toward AI authorship. AI-generated content can be useful, but \
it may contain errors or lack original insight. Please read critically."""

LABEL_B = """Likely Human-Authored — High Confidence

Our detection system is strongly confident that this text was written by \
a human. It shows the natural variability in sentence structure, vocabulary \
diversity, and authentic voice that characterise human writing. As with any \
attribution system, this is an informed estimate — not a guarantee."""

LABEL_C = """Attribution Uncertain

Our detection system could not reach a confident conclusion about whether \
this text was written by a human or generated by AI. Our two detection \
signals — one analysing writing style semantically and one measuring \
structural patterns — produced mixed or borderline results. This is common \
with short texts, highly polished writing, creative prompts designed to \
mimic human style, or non-native English prose. Treat this content as \
unverified."""


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

# Gate: confidence below this always produces Label C.
# At 0.50 this means combined ≥ 0.75 (human-leaning) or ≤ 0.25 (ai-leaning).
# Both signals must lean the same direction for A or B to appear.
# Calibrated against real signal ranges: LLM maxes at 0.90, stylometric at ~0.65.
CONFIDENCE_GATE = 0.50


def build_label(label: str, confidence: float) -> dict:
    """
    Return the transparency label variant and its full text.

    Args:
        label:      "human" | "ai" | "uncertain" (from confidence_scorer)
        confidence: float in [0.0, 1.0]

    Returns:
        {"variant": "A" | "B" | "C", "text": "..."}
    """
    # Gate: low confidence always produces the uncertain label
    if confidence < CONFIDENCE_GATE:
        return {"variant": "C", "text": LABEL_C}

    if label == "ai":
        return {"variant": "A", "text": LABEL_A}
    elif label == "human":
        return {"variant": "B", "text": LABEL_B}
    else:
        return {"variant": "C", "text": LABEL_C}